version: "3"
services: 
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins/:/var/jenkins_home
    ports:
      - "8080:8080"
    expose:
      - "8080"
      - "50000"
    privileged: true
    user: root
    restart: always
    container_name: jenkins
    environment:
      JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'